### ISSUE TITLE
Dependency on pip?

### ISSUE THREAD

**Issue by daveisfera** [youtype/types-s3transfer#1]
I just updated `boto3-stubs` and it depends on this package, and then this package is pulling in `pip`. Is that needed? If not, can it be removed?
Thanks,
Dave

**Comment by vemel** [comment]
Sure, it can be removed. Will do!

**Comment by vemel** [comment]
Just released a new version with no `pip` dependency.

**Comment by daveisfera** [comment]
Saaaaweeeet! Thanks for the quick turnaround on this!
